### ISSUE TITLE
after clicking clicking the next episode button , on the next episode when i try to use arrow keys , instead of skipping a few seconds , it jumps to the next episode

### ISSUE THREAD

**Issue by ghazzor** [akuse-app/Akuse#33] opened 2023-12-27 20:10 UTC
**Describe the bug**
as stated in the title

**To Reproduce**
1. click next episode
2. press arrow keys 
3. and you just skip that episode

**Expected behavior**
skip a few seconds

**Operative System:**
Windows 10
22H2

**Comment by ghazzor** [comment] 2023-12-27 20:28
hmm , maybe it is because the the next episode button stays "selected" after clicking it , like it happened on old websites , so pressing some key presses the next episode button ?

**Comment by aleganza** [comment] 2023-12-28 14:21
Next Episode can't stay selected as I made everything unselectable in the app
btw I just tested it but it doesn't happen to me.

**Comment by ghazzor** [comment] 2023-12-28 15:31
> Next Episode can't stay selected as I made everything unselectable in the app btw I just tested it but it doesn't happen to me. does it happen with any show?

I am not the only one , it happened to me in zom 100 , but it happens in other shows as well

**Comment by aleganza** [comment] 2023-12-28 15:46
I actually I see it happens with the Enter Key, but with arrow keys I can't reproduce it in any way. It happens sometimes or with any show?

**Comment by ghazzor** [comment] 2023-12-29 06:27
> Actually I see it happens with the Enter Key, but with arrow keys I can't reproduce it in any way. Does it happen sometimes or with any show?

any show , and with arrow keys , i never tried enter (never pressed it even once) , but it does happen with arrow keys

**Comment by aleganza** [comment] 2024-02-12 02:39
forgot about this issue, did you manage to solve it?

**Comment by ghazzor** [comment] 2024-02-15 16:10
> forgot about this issue, did you manage to solve it?

Nah , I did not test or do anything , I have exams

**Comment by ghazzor** [comment] 2024-02-23 18:07
this is not happening in v6

**Comment by aleganza** [comment] 2024-02-23 18:23
perfect

**Comment by aleganza** [comment] 2024-02-25 17:57
Just happened to me with spacebar, fixed in next update.

**Closed by aleganza** 2024-02-25 17:57 UTC
Labels: bug

**Comment by ghazzor** [comment] 2024-03-01 18:40
> Just happened to me with spacebar, fixed in next update.

hehe 

wen add hentai support

**Comment by ghazzor** [comment] 2024-03-01 18:41
> Just happened to me with spacebar, fixed in next update.

hehe

**Comment by aleganza** [comment] 2024-03-01 18:42
I read that 💀

**Comment by ghazzor** [comment] 2024-03-10 17:53
> I read that 💀

i forgot what i wrote , tell in server
